const path = require('path');
module.exports = {
  react: path.resolve('./node_modules/react'),
  bootstrap: path.resolve('./node_modules/bootstrap'),
  d3: path.resolve('./node_modules/d3'),
  gsap: path.resolve('./node_modules/gsap'),
  'd3-tip': path.resolve('./node_modules/d3-tip'),
  quill: path.resolve('./node_modules/quill'),
  emotion: path.resolve('./node_modules/emotion'),
  'react-dom': path.resolve('./node_modules/react-dom'),
  'react-infinite-calendar': path.resolve('./node_modules/react-infinite-calendar'),
  'react-material-ui-carousel': path.resolve('./node_modules/react-material-ui-carousel'),
  moment: path.resolve('./node_modules/moment'),
  'moment-timezone': path.resolve('./node_modules/moment-timezone'),
  'material-ui-popup-state': path.resolve('./node_modules/material-ui-popup-state'),
  'react-html-parser': path.resolve('./node_modules/react-html-parser'),
  lodash: path.resolve('./node_modules/lodash'),
  redux: path.resolve('./node_modules/redux'),
  'react-rte': path.resolve('./node_modules/react-rte'),
  'highlight.js': path.resolve('./node_modules/highlight.js'),
  'react-dnd': path.resolve('./node_modules/react-dnd'),
  'react-dnd-html5-backend': path.resolve('./node_modules/react-dnd-html5-backend'),
  '@reduxjs/toolkit': path.resolve('./node_modules/@reduxjs/toolkit'),
  'react-redux': path.resolve('./node_modules/react-redux'),
  'react-router-dom': path.resolve('./node_modules/react-router-dom'),
  'react-google-recaptcha': path.resolve('./node_modules/react-google-recaptcha'),
  'animated-scroll-to': path.resolve('./node_modules/animated-scroll-to'),
  'prop-types': path.resolve('./node_modules/prop-types'),
  '@emotion/react': path.resolve('./node_modules/@emotion/react'),
  '@emotion/styled': path.resolve('./node_modules/@emotion/styled'),
  '@mui/icons-material': path.resolve('./node_modules/@mui/icons-material'),
  '@mui/lab': path.resolve('./node_modules/@mui/lab'),
  '@mui/material': path.resolve('./node_modules/@mui/material'),
  '@mui/styles': path.resolve('./node_modules/@mui/styles'),
};
